version: '3.8'

services:
  webhook-redirector:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIRECT_URL=http://localhost:8080/webhook
      - LISTEN_PORT=5000
      - HOST=0.0.0.0
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s